SELECT ANIMAL_ID, NAME
FROM (
    SELECT AO.ANIMAL_ID, AO.NAME, (AO.DATETIME - AI.DATETIME) AS DURATION
    FROM ANIMAL_OUTS AO
    JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
    ORDER BY DURATION DESC
)
WHERE ROWNUM <= 2;