-- 코드를 작성해주세요
SELECT 
    E.ID AS ID,
    E.GENOTYPE AS GENOTYPE,
    C.GENOTYPE AS PARENT_GENOTYPE
FROM 
    ECOLI_DATA E
JOIN
    ECOLI_DATA C
    ON
    E.PARENT_ID = C.ID
WHERE
    (E.GENOTYPE & C.GENOTYPE) = C.GENOTYPE
ORDER BY 
    E.ID;