SELECT EXTRACT(MONTH from H.START_DATE) AS MONTH,
        H.CAR_ID,
        COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE TO_CHAR(H.START_DATE, 'YYYY-MM') >= '2022-08'
    AND TO_CHAR(H.START_DATE, 'YYYY-MM') <= '2022-10'
    and H.car_id in (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-08'
            AND TO_CHAR(START_DATE, 'YYYY-MM') <= '2022-10'
        group by car_id
        having count(*) >= 5
    )
GROUP BY EXTRACT(MONTH FROM H.START_DATE), H.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;