SELECT GROUPING.CATEGORY, GROUPING.MAX_PRICE, ORI.PRODUCT_NAME
FROM FOOD_PRODUCT ORI
JOIN
(
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE 
FROM FOOD_PRODUCT 
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
GROUP BY CATEGORY
) GROUPING
ON ORI.CATEGORY = GROUPING.CATEGORY AND ORI.PRICE = GROUPING.MAX_PRICE
ORDER BY GROUPING.MAX_PRICE DESC